// lib/services/hive_service.dart
import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:path_provider/path_provider.dart';
import '../models/envelope.dart';
import '../models/account.dart';
import '../models/envelope_group.dart';
import '../models/transaction.dart';
import '../models/scheduled_payment.dart';
import '../models/pay_day_settings.dart';

/// Service to initialize Hive local storage
class HiveService {
  static bool _initialized = false;

  /// Initialize Hive and register all adapters
  ///
  /// Must be called before using any Hive boxes.
  /// Safe to call multiple times (idempotent).
  static Future<void> init() async {
    if (_initialized) {
      debugPrint('[HiveService] Already initialized, skipping');
      return;
    }

    debugPrint('[HiveService] Initializing Hive...');

    // Initialize Hive with app directory
    final appDocDir = await getApplicationDocumentsDirectory();
    await Hive.initFlutter(appDocDir.path);

    // Register all model adapters (generated by build_runner)
    Hive.registerAdapter(EnvelopeAdapter());
    Hive.registerAdapter(AccountAdapter());
    Hive.registerAdapter(AccountTypeAdapter());
    Hive.registerAdapter(EnvelopeGroupAdapter());
    Hive.registerAdapter(TransactionAdapter());
    Hive.registerAdapter(TransactionTypeAdapter());
    Hive.registerAdapter(TransferDirectionAdapter());
    Hive.registerAdapter(ScheduledPaymentAdapter());
    Hive.registerAdapter(PaymentFrequencyUnitAdapter());
    Hive.registerAdapter(PayDaySettingsAdapter());

    // Open all boxes
    await Hive.openBox<Envelope>('envelopes');
    await Hive.openBox<Account>('accounts');
    await Hive.openBox<EnvelopeGroup>('groups');
    await Hive.openBox<Transaction>('transactions');
    await Hive.openBox<ScheduledPayment>('scheduledPayments');
    await Hive.openBox<PayDaySettings>('payDaySettings');

    _initialized = true;
    debugPrint('[HiveService] ✅ Hive initialized successfully');
  }

  /// Get a Hive box (must call init() first)
  static Box<T> getBox<T>(String name) {
    if (!_initialized) {
      throw Exception('HiveService not initialized. Call HiveService.init() first.');
    }
    return Hive.box<T>(name);
  }

  /// Close all Hive boxes (call on app termination)
  static Future<void> close() async {
    await Hive.close();
    _initialized = false;
    debugPrint('[HiveService] Hive closed');
  }
}
