// lib/services/hive_service.dart
import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:path_provider/path_provider.dart';
import '../models/envelope.dart';
import '../models/account.dart';
import '../models/envelope_group.dart';
import '../models/transaction.dart';
import '../models/scheduled_payment.dart';
import '../models/pay_day_settings.dart';
import '../models/app_notification.dart';

/// Custom exception for Hive initialization failures
class HiveInitException implements Exception {
  final String message;
  HiveInitException(this.message);

  @override
  String toString() => 'HiveInitException: $message';
}

/// Service to initialize Hive local storage
class HiveService {
  static bool _initialized = false;
  static final List<String> _openBoxes = [];

  /// Initialize Hive and register all adapters
  ///
  /// Must be called before using any Hive boxes.
  /// Safe to call multiple times (idempotent).
  /// Throws HiveInitException if initialization fails.
  static Future<void> init() async {
    if (_initialized) {
      debugPrint('[HiveService] Already initialized, skipping');
      return;
    }

    debugPrint('[HiveService] Initializing Hive...');

    try {
      // Initialize Hive with app directory
      final appDocDir = await getApplicationDocumentsDirectory();
      debugPrint('[HiveService] App documents directory: ${appDocDir.path}');
      await Hive.initFlutter(appDocDir.path);
      debugPrint('[HiveService] ✅ Hive.initFlutter completed');

      // Register all model adapters (generated by build_runner)
      try {
        Hive.registerAdapter(EnvelopeAdapter());
        Hive.registerAdapter(AccountAdapter());
        Hive.registerAdapter(AccountTypeAdapter());
        Hive.registerAdapter(EnvelopeGroupAdapter());
        Hive.registerAdapter(TransactionAdapter());
        Hive.registerAdapter(TransactionTypeAdapter());
        Hive.registerAdapter(TransferDirectionAdapter());
        Hive.registerAdapter(ScheduledPaymentAdapter());
        Hive.registerAdapter(PaymentFrequencyUnitAdapter());
        Hive.registerAdapter(ScheduledPaymentTypeAdapter());
        Hive.registerAdapter(PayDaySettingsAdapter());
        Hive.registerAdapter(AppNotificationAdapter());
        Hive.registerAdapter(NotificationTypeAdapter());
        debugPrint('[HiveService] ✅ All adapters registered');
      } catch (e) {
        // Adapters might already be registered on hot reload
        debugPrint('[HiveService] ⚠️ Adapter registration error (might be already registered): $e');
      }

      // Open all boxes with individual error handling
      // IMPORTANT: Must open boxes with explicit types to avoid Box<dynamic> errors
      try {
        if (!Hive.isBoxOpen('envelopes')) {
          await Hive.openBox<Envelope>('envelopes');
          _openBoxes.add('envelopes');
          debugPrint('[HiveService] ✅ Opened box: envelopes');
        } else {
          _openBoxes.add('envelopes');
          debugPrint('[HiveService] ℹ️ Box already open: envelopes');
        }
      } catch (e) {
        debugPrint('[HiveService] ❌ Failed to open box envelopes: $e');
        throw HiveInitException('Failed to open box envelopes: $e');
      }

      try {
        if (!Hive.isBoxOpen('accounts')) {
          await Hive.openBox<Account>('accounts');
          _openBoxes.add('accounts');
          debugPrint('[HiveService] ✅ Opened box: accounts');
        } else {
          _openBoxes.add('accounts');
          debugPrint('[HiveService] ℹ️ Box already open: accounts');
        }
      } catch (e) {
        debugPrint('[HiveService] ❌ Failed to open box accounts: $e');
        throw HiveInitException('Failed to open box accounts: $e');
      }

      try {
        if (!Hive.isBoxOpen('groups')) {
          await Hive.openBox<EnvelopeGroup>('groups');
          _openBoxes.add('groups');
          debugPrint('[HiveService] ✅ Opened box: groups');
        } else {
          _openBoxes.add('groups');
          debugPrint('[HiveService] ℹ️ Box already open: groups');
        }
      } catch (e) {
        debugPrint('[HiveService] ❌ Failed to open box groups: $e');
        throw HiveInitException('Failed to open box groups: $e');
      }

      try {
        if (!Hive.isBoxOpen('transactions')) {
          await Hive.openBox<Transaction>('transactions');
          _openBoxes.add('transactions');
          debugPrint('[HiveService] ✅ Opened box: transactions');
        } else {
          _openBoxes.add('transactions');
          debugPrint('[HiveService] ℹ️ Box already open: transactions');
        }
      } catch (e) {
        debugPrint('[HiveService] ❌ Failed to open box transactions: $e');
        throw HiveInitException('Failed to open box transactions: $e');
      }

      try {
        if (!Hive.isBoxOpen('scheduledPayments')) {
          await Hive.openBox<ScheduledPayment>('scheduledPayments');
          _openBoxes.add('scheduledPayments');
          debugPrint('[HiveService] ✅ Opened box: scheduledPayments');
        } else {
          _openBoxes.add('scheduledPayments');
          debugPrint('[HiveService] ℹ️ Box already open: scheduledPayments');
        }
      } catch (e) {
        debugPrint('[HiveService] ❌ Failed to open box scheduledPayments: $e');
        throw HiveInitException('Failed to open box scheduledPayments: $e');
      }

      try {
        if (!Hive.isBoxOpen('payDaySettings')) {
          await Hive.openBox<PayDaySettings>('payDaySettings');
          _openBoxes.add('payDaySettings');
          debugPrint('[HiveService] ✅ Opened box: payDaySettings');
        } else {
          _openBoxes.add('payDaySettings');
          debugPrint('[HiveService] ℹ️ Box already open: payDaySettings');
        }
      } catch (e) {
        debugPrint('[HiveService] ❌ Failed to open box payDaySettings: $e');
        throw HiveInitException('Failed to open box payDaySettings: $e');
      }

      try {
        if (!Hive.isBoxOpen('notifications')) {
          await Hive.openBox<AppNotification>('notifications');
          _openBoxes.add('notifications');
          debugPrint('[HiveService] ✅ Opened box: notifications');
        } else {
          _openBoxes.add('notifications');
          debugPrint('[HiveService] ℹ️ Box already open: notifications');
        }
      } catch (e) {
        debugPrint('[HiveService] ❌ Failed to open box notifications: $e');
        throw HiveInitException('Failed to open box notifications: $e');
      }

      _initialized = true;
      debugPrint('[HiveService] ✅ Hive initialized successfully');
      debugPrint('[HiveService] ✅ Boxes opened: $_openBoxes');
    } catch (e, stackTrace) {
      _initialized = false;
      _openBoxes.clear();
      debugPrint('[HiveService] ❌ Hive initialization FAILED');
      debugPrint('[HiveService] Error: $e');
      debugPrint('[HiveService] Stack trace: $stackTrace');
      throw HiveInitException('Hive initialization failed: $e');
    }
  }

  /// Get a Hive box (must call init() first)
  static Box<T> getBox<T>(String name) {
    if (!_initialized) {
      throw Exception('HiveService not initialized. Call HiveService.init() first.');
    }
    if (!_openBoxes.contains(name)) {
      throw Exception('Box "$name" was not successfully opened during initialization.');
    }
    if (!Hive.isBoxOpen(name)) {
      throw Exception('Box "$name" is not open. This should not happen after successful init.');
    }
    return Hive.box<T>(name);
  }

  /// Check if HiveService is properly initialized and all boxes are open
  static bool get isInitialized => _initialized;

  /// Get list of successfully opened boxes
  static List<String> get openBoxes => List.unmodifiable(_openBoxes);

  /// Validate that all required boxes are open and ready
  static Map<String, bool> validateBoxes() {
    final requiredBoxes = [
      'envelopes',
      'accounts',
      'groups',
      'transactions',
      'scheduledPayments',
      'payDaySettings',
      'notifications',
    ];

    final status = <String, bool>{};
    for (final boxName in requiredBoxes) {
      status[boxName] = _openBoxes.contains(boxName) && Hive.isBoxOpen(boxName);
    }
    return status;
  }

  /// Close all Hive boxes (call on app termination)
  static Future<void> close() async {
    await Hive.close();
    _initialized = false;
    debugPrint('[HiveService] Hive closed');
  }
}
